# Generated by Django 4.0.1 on 2022-02-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
    ]
