# Generated by Django 4.0.1 on 2022-02-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0005_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursesmap',
            name='semester',
            field=models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter')], default='FA', max_length=2),
        ),
        migrations.AddField(
            model_name='usercoursesmap',
            name='year_taken',
            field=models.IntegerField(blank=True, default=2022),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
