# Generated by Django 4.0.1 on 2022-02-08 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0006_usercoursesmap_semester_usercoursesmap_year_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='school_offering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log_in.school'),
        ),
        migrations.AlterField(
            model_name='usercoursesmap',
            name='taking_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_in.course'),
        ),
        migrations.DeleteModel(
            name='SchoolCoursesMap',
        ),
    ]
