# Generated by Django 4.0.1 on 2022-02-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0008_alter_course_course_code_course_unique_school_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursesmap',
            name='semester',
            field=models.CharField(choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')], default=2, max_length=2),
        ),
    ]
