# Generated by Django 4.0.1 on 2022-02-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0010_alter_usercoursesmap_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursesmap',
            name='semester',
            field=models.IntegerField(choices=[(0, 'Spring'), (1, 'Summer'), (2, 'Fall'), (3, 'Winter')], default=2),
        ),
    ]
