# Generated by Django 4.0.1 on 2022-02-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0012_tutorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('date_and_time', models.DateTimeField()),
                ('location', models.CharField(max_length=50)),
            ],
        ),
    ]
