# Generated by Django 4.0.1 on 2022-02-16 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0013_apptdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=0)),
                ('approval', models.BooleanField()),
                ('notes', models.TextField()),
                ('appt_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_in.apptdetails')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('tutor_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
