# Generated by Django 4.0.1 on 2022-02-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0015_alter_apptrequests_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptrequests',
            name='approval',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
