# Generated by Django 4.0.1 on 2022-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0016_alter_apptrequests_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptrequests',
            name='pending',
            field=models.BooleanField(default=1),
        ),
    ]
