# Generated by Django 4.0.1 on 2022-03-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_in', '0018_alter_apptrequests_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apptrequests',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
